apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
  namespace: kagent
type: Opaque
stringData:
  SLACK_BOT_TOKEN: "xoxb-4829ffbUx"
  SLACK_APP_TOKEN: "xapp-1-A0fffc59ccdfacd22bf88faec3"
  KAGENT_A2A_URL: "http://kagent-controller.kagent.svc.cluster.local:8083"
  SLACK_TEAM_ID: "T0fV"
  SLACK_CHANNEL_IDS: "C04f"
