---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kagent-slack-bot
  namespace: kagent
  labels:
    app: kagent-slack-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kagent-slack-bot
  template:
    metadata:
      labels:
        app: kagent-slack-bot
    spec:
      # Security context for the pod (2025 best practices)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: bot
        # Replace with your image: your-registry/kagent-slack-bot:latest
        # Examples:
        #   - docker.io/username/kagent-slack-bot:latest
        #   - ghcr.io/username/kagent-slack-bot:latest
        #   - gcr.io/project-id/kagent-slack-bot:latest
        image: sebbycorp/kagent-slack-bot:latest
        imagePullPolicy: Always

        # Container security context (fixes pod security restricted warnings)
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL

        env:
        # Slack tokens from secret
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-credentials
              key: SLACK_BOT_TOKEN
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-credentials
              key: SLACK_APP_TOKEN

        # Kagent Configuration - Separate components for flexibility
        # Change these values to match your Kagent deployment
        - name: KAGENT_BASE_URL
          value: "http://kagent-controller.kagent.svc.cluster.local:8083"
        - name: KAGENT_NAMESPACE
          value: "kagent"
        - name: KAGENT_AGENT_NAME
          value: "slackbot-k8s-agent"
        
        # Temporary directory for Python (needed with readOnlyRootFilesystem)
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: python-cache
          mountPath: /home/kagent/.cache

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        # Liveness probe - check if Python process is responsive
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        # Readiness probe - bot must be running to be ready
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5

      # Volumes for temporary files (required with readOnlyRootFilesystem)
      volumes:
      - name: tmp
        emptyDir: {}
      - name: python-cache
        emptyDir: {}

      restartPolicy: Always

      # Automatically mount service account token only if needed
      automountServiceAccountToken: false